### ISSUE TITLE
ci: Container images release

### ISSUE THREAD

**Issue by mudler** [masa-finance/masa-bittensor#109]
As part of the release process there should be some consumable artifacts.

Can we have for instance a container image that users can pull?

Have a github action that deploys the opentensor subtensor and runs the initial create subnet:

This could replace the running "devnet" that have deployed based on / triggered by updates to the main branch of our fork of opentensor/subtensor, so that we control when we redeploy updates to main on our own public devnet / testnet chain
This should optionally allow for updates to our private devnet code without necessarily starting with a fresh chain.
This may involve a more volatile private devnet where we run branches other than main when testing changes to the subtensor codebase, and should also optionally allow retaining or starting from a fresh chain database.
Github action could also provision required infra to run subtensor / devnet on, or that could be handled separately (as with oracle nodes vs. oracle app currently).

## Acceptance criteria
- [ ] we have a GHA workflow that publishes container images when the bittensor repository is tagged
- [x] the images are public and can be pulled by everyone
- [x] the images don't have sensitive configurations, but can be used with specific network configurations (E.g. testnet, devnet, ecc)

**Comment by 5u6r054** [comment]
Now there is a GHA workflow that creates 5 public images under docker compose that anyone can pull. There is a Makefile, and a readme.md has been updated, so now you can clone the repo and do `make up` and it will pull the latest 5 images (subtensor, subnet, validator, miner, protocol) and start them all. `make logs` will show the output. The result is you can go to localhost:8000/docs and see docs of the validator API, you can call them on port 8080. A masa protocol node is up on port 8081 and connected to masa testnet, and responds to requests from the miner via the validator.

**Comment by mudler** [comment]
![Screenshot from 2024-07-08 15-02-59](https://github.com/masa-finance/masa-bittensor/assets/2420543/6fa3b7ed-cb5e-411e-8b04-16cd20e3289c)

Seems it doesn't work for tagged releases - reopening

**Comment by Luka-Loncar** [comment]
Tagging is not implemented here with GHA - it is covered with other tasks.
