### ISSUE TITLE
Integration tests for validator

### ISSUE THREAD

**Issue by hide-on-bush-x** [masa-finance/masa-bittensor#118]
### Based on #99 
We need to test the validator every time we push new code, so, it is required to build some scripts or code to test some of the vital interactions with the miners and the metagraph

### Testing list
- [ ]  Is the validator calling miners? Deploy a miner ( Dependency on docker setup ) and check if the miner gets a call from the deployed validator

- [ ] Is the validator ignoring miners that don't meet the selection criteria? ( deploy a miner that doesn't meet the selection criteria and check if it's being ignored )

- [ ] Setting weights ( Check if the weights are being set correctly after some calls to miners ) `There is an example on the  parent ticket #99 ` ([link](https://github.com/masa-finance/masa-bittensor/issues/99#issuecomment-2191985434))

- [ ] Check that the scores are being updated ( deploy a miner and make some calls to the validator api, check that the state.pt file is updated )

This scripts must be called from the GH actions set up on #117

**Comment by juanmanso** [comment]
Based on the description, would you agree @hide-on-bush-x that this task is:
- Blocked by #117 

?

If so, i'd suggest to add the blocker label here

**Comment by Luka-Loncar** [comment]
We need to groom this on the next planning and get final agreement between eng team and devops on how the integration tests should look like and how they should be executed.

**Comment by Luka-Loncar** [comment]
Closing this because it is covered in #120 and #121
