### ISSUE TITLE
Return highest scoring response to the API

### ISSUE THREAD

**Issue by grantdfoster** [masa-finance/masa-bittensor#124]
From an API perspective, we want to return what the validator judges as the "best" response, or highest scoring, not a list of sanitized responses based on pre-defined types.

**Comment by juanmanso** [comment]
This should be fixed by changing the return object from the list to the first element [here](https://github.com/masa-finance/masa-bittensor/blob/a5e1c873251f284daa70fbf54af925f5c2a2226b/masa/validator/forwarder.py#L87) right?

```diff
        print("FINAL RESPONSES ------------------------------------------------")
        print(response_with_uids)
        
-        return response_with_uids
+        return response_with_uids[0]
```

(Aside from the fact that the return type should be changed as well)

**Comment by juanmanso** [comment]
> This should be fixed by changing the return object from the list to the first element [here](https://github.com/masa-finance/masa-bittensor/blob/a5e1c873251f284daa70fbf54af925f5c2a2226b/masa/validator/forwarder.py#L87) right?
> 
>         print("FINAL RESPONSES ------------------------------------------------")
>         print(response_with_uids)
>         
> -        return response_with_uids
> +        return response_with_uids[0]
> (Aside from the fact that the return type should be changed as well)

Isn't this blocked also by [masa-bittensor/issues#197](https://github.com/masa-finance/issues/issues/197)? Or could we fix it and then have the scoring be worked on in parallel 🤔 (I think we can but just checking here)

**Comment by mudler** [comment]
this is low hanging fruit, and what we could actually do is mutate the behavior such having a debug flag that returns all the scores, and when in product mode, returns only the highest score.

**Comment by mudler** [comment]
Outcome from planning: even better to have a separate endpoint and avoiding any user option, or maybe a parameter to the API endpoint
