### ISSUE TITLE
Create release for v0.7 notes with features

### ISSUE THREAD

**Issue by Luka-Loncar** [masa-finance/masa-bittensor#137]
After we have a github release, and automated release notes are generated, we want to have a more "human readable" release note form to show in https://developers.masa.ai/docs/masa-subnet/RELEASE_NOTES

**Comment by obasilakis** [comment]
Release notes available [here](https://github.com/masa-finance/masa-bittensor/releases/tag/v0.5.0).

**Comment by juanmanso** [comment]
Quick question here, aren't these human readable already? Or should this be more like marketing kind of readable?

- https://github.com/masa-finance/masa-bittensor/releases/tag/v0.5.0

If so, I'd suggest we pass this task to stakeholders to perform the update based on the automated ones.

**Comment by juanmanso** [comment]
> Quick question here, aren't these human readable already? Or should this be more like marketing kind of readable?
> 
> * https://github.com/masa-finance/masa-bittensor/releases/tag/v0.5.0
> 
> If so, I'd suggest we pass this task to stakeholders to perform the update based on the automated ones.

This might be directly related to [roadmap/issues#55](https://github.com/masa-finance/roadmap/issues/55), right? Should we close this since the update would be taken care of by the output of [roadmap/issues#55](https://github.com/masa-finance/roadmap/issues/55)?

**Comment by mudler** [comment]
Closing in favor of https://github.com/masa-finance/roadmap/issues/55
