### ISSUE TITLE
V1 - Create Subnet Validator

### ISSUE THREAD

**Issue by Luka-Loncar** [masa-finance/masa-bittensor#14]
List of tasks for V1:

- [x] #8 
- [ ] #10 
- [x] #11 
- [x] #13 

List of taks that are not in V1 scope:

- [ ] #9 
- [ ] #12 

### Objective:

Establish the process by which the subnet validator will interact with miners, including sending requests, receiving responses, and scoring those responses using the provided `forward.py`, `reward.py`, and `protocol.py` files.

### Acceptance Criteria:

- Validator can send well-formed requests to miners using the protocol.
- Validator processes and logs all miner responses.
- Responses are scored accurately and fairly based on predefined criteria.
- Miner scores in the metagraph are updated accordingly.

### Resources:

- [[forward.py](notion://www.notion.so/masafinance/template/validator/forward.py)](notion://www.notion.so/masafinance/template/validator/forward.py): Validator's main loop for sending requests and processing responses.
- [[reward.py](notion://www.notion.so/masafinance/template/validator/reward.py)](notion://www.notion.so/masafinance/template/validator/reward.py): Contains the logic for scoring miner responses.
- [[protocol.py](notion://www.notion.so/masafinance/template/protocol.py)](notion://www.notion.so/masafinance/template/protocol.py): Defines the protocol used for communication between validators and miners.

### Notes:

- Define miner selection criteria
- Define reward logic and what the correct response should be, i.e. what the validator checks against
- Management of the blacklist logic (v2)

### Outstanding Questions:

- [ ]  **Miner Selection Criteria**
    - What criteria should the validator use to select miners for querying?
    - Should the selection be random, performance-based, or a combination of both?
- [ ]  **Query Frequency and Timing**
    - How frequently should the validator send out queries?
    - Should there be a fixed schedule or should it be event-driven based on certain conditions?
- [ ]  **Handling Miner Non-responsiveness**
    - How should the validator handle situations where a miner does not respond to a query?
    - What mechanisms should be in place to ensure fairness and minimize the impact on the miner's score due to transient issues?

**Comment by mudler** [comment]
Closing as not relevant anymore
