### ISSUE TITLE
Update requirements.txt

### ISSUE THREAD

**Issue by juanmanso** [masa-finance/masa-bittensor#144]
The last time the `requirements.txt` was updated was a month ago. It could be possible that some dependencies were added which are not there.

Most importantly (if things are working) we could [follow @teslashibe's suggestion made on Slack.](https://masafinance.slack.com/archives/C0742F6KXB8/p1719599467709769) It would be a good idea to **fix the versions** of those packages to have a stable environment. 

## Questions
- Should we support non-conda environments?
  - If so, we need to test them

## Acceptance criteria
- User can run a miner with a fresh conda environment
- User can run a validator with a fresh conda environment
- User can get information of subnets and wallets using `btcli` without issues
- Packages' versions are fixed

**Comment by giovaroma** [comment]
BTCLI new version having issues.  If you have an older version of Bittensor there are issues. Reporting issues with new versions 7.2 Bittensor. Will do testing today to either downgrade to 7.2 or 7.1, 7.3 is not working. @grantdfoster and @hide-on-bush-x working on solution.

**Comment by grantdfoster** [comment]
Updated the PR to include BTCLI 7.2, will continue testing w/ this version
