### ISSUE TITLE
Figure out how to set axon's version

### ISSUE THREAD

**Issue by juanmanso** [masa-finance/masa-bittensor#145]
## Goal

We want to restrict miners and validators running old versions of our code. That means that if someone spins a neuron with 0.1.0 and we are supporting from 0.1.1 onwards, it would be ignored.

This should not be mistaken with a malicious actor blacklisting, but rather a fail safe for users to know they should update to latest versions of our code

**Comment by juanmanso** [comment]
🟢 **[UPDATE]** _Found where axon's info is set_

| ![Image](https://github.com/masa-finance/masa-bittensor/assets/21087992/7854cb2b-e695-403c-9993-55951088a662)|
| :--: |

As shown on the image above, `bittensor's` package is in charge of the `info` method which sets the `AxonInfo`. In particular, the version is defined by bittensor's version.


If we need to tweak this, we require forking/overloading the axon instance as [suggested on discord by Rapido [τ, ⛏]](https://discord.com/channels/1120750674595024897/1146169709683822643/1190063733817491587):

| ![Image](https://github.com/masa-finance/masa-bittensor/assets/21087992/d2cd163e-f2af-484d-88f4-475e0f4dd6dc) |
| :---: |


Based on this, I'd suggest we look for another way to check the version of the app. Maybe create a Miner Metadata object of some sort as [it is been done by SN15](https://github.com/blockchain-insights/blockchain-data-subnet/blob/8a1d67842a1b8162121c464168dd4c9b0be77fca/neurons/storage.py#L68):
```py
        metadata = MinerMetadata(
            sb=start_block,
            lb=last_block,
            bl=balance_model_last_block,
            n=get_network_id(self.config.network),
            cv=insights.__version__,
            lv=llm_version
        )
```

**Comment by juanmanso** [comment]
@hide-on-bush-x what do you think about this ☝

**Comment by hide-on-bush-x** [comment]
Great reseearch, super helpful, thank you @juanmanso!
