### ISSUE TITLE
V1 - Create Subnet Miner

### ISSUE THREAD

**Issue by Luka-Loncar** [masa-finance/masa-bittensor#15]
Implement Twitter Data Endpoints (MVP) Subnet Miner Code

### Tasks:

- [x] #17 
- [x] #18
- [x] #19 

### Objective:

Develop a subnet miner within the Bittensor network that interfaces with the Masa Protocol worker node API to retrieve Twitter data. The miner will provide endpoints for three specific Twitter-related queries: profile information, recent tweets by keyword, and a user's followers list.

### Acceptance Criteria:

- Miner code can accurately fetch and return Twitter profile information.
- Miner code successfully retrieves recent tweets based on a provided keyword.
- Miner code can fetch a user's followers list upto the maximum number specified in the query parameter
- All miner endpoints are registered and served using the Bittensor API.
- The miner adheres to the Masa Protocol worker node API's rate limits and handles exceptions properly.
- Documentation is provided for each miner function, detailing inputs, outputs, and behavior.

### Resources:

- [[Bittensor API Documentation](https://docs.bittensor.com/python-api/html/autoapi/bittensor/index.html)](https://docs.bittensor.com/python-api/html/autoapi/bittensor/index.html)
- [[Masa Protocol Worker Node API](http://localhost:8080/swagger/index.html#/)](http://localhost:8080/swagger/index.html#/)

### Development Steps:

1. Set up a Bittensor wallet and neuron using the Bittensor API.
2. Register the miner's endpoints with the Bittensor network.
3. Implement the Twitter data retrieval logic using the Masa Protocol worker node API.
4. Serve the miner's endpoints using Bittensor's Axon server.
5. Test the miner's functionality and handle edge cases.
6. Document the miner's code and usage instructions.

**Comment by mudler** [comment]
Closing as not relevant anymore
