### ISSUE TITLE
Level=error logs masa-node Bittensor testnet

### ISSUE THREAD

**Issue by Naesmal** [masa-finance/masa-bittensor#157]
![Screenshot_20240712_140128](https://github.com/user-attachments/assets/8e5a7c24-6d15-487e-9955-0a5956c44a1e)
How to resolve the "level=error" issue that occurs during mining in the Masa Bittensor testnet ```make run-miner```

**Comment by grantdfoster** [comment]
This is an old issue w/ the masa protocol, not necessarily related to the Bittensor subnet.  Has been resolved in recent releases of the protocol.
