### ISSUE TITLE
after update : cd masa-bittensor and "git pull" that have error : RuntimeError: PytorchStreamReader failed locating file data.pkl: file not found

### ISSUE THREAD

**Issue by IONodeOnline** [masa-finance/masa-bittensor#169]
2024-08-01 12:26:43.414 |       INFO       | bittensor:loggingmachine.py:359 |  - Setting up bittensor objects. -
2024-08-01 12:26:43.817 |       INFO       | bittensor:loggingmachine.py:359 |  - Connected to unknown network and ws://100.28.51.29:9945. -
2024-08-01 12:26:46.175 |       INFO       | bittensor:loggingmachine.py:359 |  - Wallet: wallet(miner, default, ~/.bittensor/wallets/) -
2024-08-01 12:26:46.175 |       INFO       | bittensor:loggingmachine.py:359 |  - Subtensor: subtensor(unknown, ws://100.28.51.29:9945) -
2024-08-01 12:26:46.176 |       INFO       | bittensor:loggingmachine.py:359 |  - Metagraph: metagraph(netuid:1, n:256, block:157178, network:unknown) -
2024-08-01 12:26:46.379 |       INFO       | bittensor:loggingmachine.py:359 |  - Running neuron on subnet: 1 with uid 68 using network: ws://100.28.51.29:9945 -
2024-08-01 12:26:46.472 |       INFO       | bittensor:loggingmachine.py:359 |  - Attaching forward function to miner axon. -
2024-08-01 12:26:46.475 |       INFO       | bittensor:loggingmachine.py:359 |  - Axon created: Axon([::], 8091, 5CqyrNyhjUQAUJ1BoufhiGt15w4n33pWmxEme7pi612tyxdG, stopped, ['Synapse', 'Request']) -
2024-08-01 12:26:46.475 |       INFO       | bittensor:loggingmachine.py:359 |  - Loading miner state. -
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ /root/masa-bittensor/neurons/miner.py:239 in <module>                                            │
│                                                                                                  │
│   236                                                                                            │
│   237                                                                                            │
│   238 if __name__ == "__main__":                                                                 │
│ ❱ 239 │   with Miner() as miner:                                                                 │
│   240 │   │   while True:                                                                        │
│   241 │   │   │   print("Miner running...", time.time())                                         │
│   242 │   │   │   time.sleep(5)                                                                  │
│                                                                                                  │
│ /root/masa-bittensor/neurons/miner.py:43 in __init__                                             │
│                                                                                                  │
│    40                                                                                            │
│    41 class Miner(BaseMinerNeuron):                                                              │
│    42 │   def __init__(self, config=None):                                                       │
│ ❱  43 │   │   super(Miner, self).__init__(config=config)                                         │
│    44 │   │   self.axon.attach(forward_fn=forward_ping)                                          │
│    45 │   │   bt.logging.info("Miner initialized with config: {}".format(config))                │
│    46                                                                                            │
│                                                                                                  │
│ /root/masa-bittensor/masa/base/miner.py:84 in __init__                                           │
│                                                                                                  │
│    81 │   │   │   self.config.blacklist.min_stake_required                                       │
│    82 │   │   )  # note, this will be variable per environment                                   │
│    83 │   │                                                                                      │
│ ❱  84 │   │   self.load_state()                                                                  │
│    85 │                                                                                          │
│    86 │   def run(self):                                                                         │
│    87 │   │   """                                                                                │
│                                                                                                  │
│ /root/masa-bittensor/masa/base/miner.py:226 in load_state                                        │
│                                                                                                  │
│   223 │   │   # Load the state of the miner from file.                                           │
│   224 │   │   state_path = self.config.neuron.full_path + "/state.pt"                            │
│   225 │   │   if os.path.isfile(state_path):                                                     │
│ ❱ 226 │   │   │   state = torch.load(state_path)                                                 │
│   227 │   │   │   self.neurons_permit_stake = state.get("neurons_permit_stake", {})              │
│   228 │   │   else:                                                                              │
│   229 │   │   │   bt.logging.warning(                                                            │
│                                                                                                  │
│ /root/miniconda3/envs/bittensor/lib/python3.12/site-packages/torch/serialization.py:1025 in load │
│                                                                                                  │
│   1022 │   │   │   │   │   │   │   │   │    **pickle_load_args)                                  │
│   1023 │   │   │   │   │   except RuntimeError as e:                                             │
│   1024 │   │   │   │   │   │   raise pickle.UnpicklingError(UNSAFE_MESSAGE + str(e)) from None   │
│ ❱ 1025 │   │   │   │   return _load(opened_zipfile,                                              │
│   1026 │   │   │   │   │   │   │    map_location,                                                │
│   1027 │   │   │   │   │   │   │    pickle_module,                                               │
│   1028 │   │   │   │   │   │   │    overall_storage=overall_storage,                             │
│                                                                                                  │
│ /root/miniconda3/envs/bittensor/lib/python3.12/site-packages/torch/serialization.py:1442 in      │
│ _load                                                                                            │
│                                                                                                  │
│   1439 │   │   │   return super().find_class(mod_name, name)                                     │
│   1440 │                                                                                         │
│   1441 │   # Load the data (which may in turn use `persistent_load` to load tensors)             │
│ ❱ 1442 │   data_file = io.BytesIO(zip_file.get_record(pickle_file))                              │
│   1443 │                                                                                         │
│   1444 │   unpickler = UnpicklerWrapper(data_file, **pickle_load_args)                           │
│   1445 │   unpickler.persistent_load = persistent_load                                           │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
RuntimeError: PytorchStreamReader failed locating file data.pkl: file not found

**Comment by hide-on-bush-x** [comment]
Hello @IONodeOnline, sorry to hear that you are having trouble with this
Could you tell me which version of bittensor you are running? 
```btcli -h```

**Comment by grantdfoster** [comment]
Another option is to remove the miner's `state.pt` file and see if that works!  I have experienced this in the past on the validator side, so could be the case here.

`~/.bittensor/miners/miner/default/netuid1/miner/state.pt`
