### ISSUE TITLE
feature: endpoint for getting a leaderboard based on how much TAO neurons have 

### ISSUE THREAD

**Issue by hide-on-bush-x** [masa-finance/masa-bittensor#170]
It is required to find a better way to calculate the leaderboard for the incentivized testnet

Decided that we are going to use the amount of tao each key has to display this new leaderboard

**Comment by hide-on-bush-x** [comment]
![Image](https://github.com/user-attachments/assets/ce546253-c87d-450c-95a6-d007e40a0c63)
 
Endpoint seems to be working!

**Comment by grantdfoster** [comment]
@hide-on-bush-x taking a look at this ticket - is there no code associated w/ it?  I am curious how you are fetching balances - it _looks like_ you're grabbing coldkey balances but we'll actually want to grab hotkey "balances", i.e. tStake on the metagraph, no?  Just want to get on the same page / make sure I'm thinking about this correctly!

**Comment by hide-on-bush-x** [comment]
@grantdfoster Hey! attached the corresponding PR to this ticket
I am grabbing cold keys instead of hotkeys, that made sense to me and at least thought that the coldkey balance is the sum of all the staked balances on the associated hotkeys. Ill do some testing around that to make sure I am getting all the required balances
