### ISSUE TITLE
Properly define a structure for rewards 

### ISSUE THREAD

**Issue by hide-on-bush-x** [masa-finance/masa-bittensor#172]
### Definition
As shown in https://github.com/masa-finance/masa-bittensor/pull/166 we are getting a new method for calculating scoring and rewards. 
But the values used in here were not studied in detail, we should do some testing and define what is the best configuration for us 

### What can be configured?
( Based on an initial score of 1 - Time improvement score, and comparing the response agains a source of truth, when the responses didn't get 1 as score )

- Amount of score lost per missing root field 
- Amount of score lost per missing field on an list
- Amount of score lost per different value in the same key
- Amount of score lost per different value in the same key on a list
- Amount of score lost based on length difference on a list 
- Amount of score allocated for time improvement 

### Acceptance criteria
 
- [ ] Configurable constants where someone like @theMultitude can play and fine tune the rewards a validator is returning
- [ ] A well defined doc for this

**Comment by Luka-Loncar** [comment]
Closing this one - creating a Spike and adding to v1.0 here. @teslashibe is adding ticket #242
