### ISSUE TITLE
Spike: miners are incentivized to do work "faster" than protocol and circumvent it entirely to gain advantage

### ISSUE THREAD

**Issue by Luka-Loncar** [masa-finance/masa-bittensor#207]

**Comment by grantdfoster** [comment]
We likely won't see this behavior until the mainnet has been out for a few weeks / months, but over time miners will get greedy and try to stand out from the herd, while still supplying "accurate" data.  One way to do this (for Twitter, for example), would be to build a better / faster / stronger scraper, and thus having lower latency / better scoring.  This would only take effect once latency is layered into our scoring.

**Comment by Luka-Loncar** [comment]
This one is dependent on #172
