### ISSUE TITLE
Spike: auto-updating when we version bump

### ISSUE THREAD

**Issue by Luka-Loncar** [masa-finance/masa-bittensor#208]
what does that look like, how do other subnets do it, etc

**Comment by grantdfoster** [comment]
Subnet 19 is a good one to look at, but _many_ subnets incorporate auto updating.  Typical flow is the run processes in the background with `pm2` and periodically check the latest release on Github... if a new release is released, the auto-updater fetches said code and re-runs the miner and/or validator.

While this ensures every neuron on the network will be running the latest code when we bump versions, there is the caveat that if a bug was in the release, it would have catastrophic effect.

**Comment by mudler** [comment]
Let's not jump the gun on this one until we have a test suite which allows us to be more confident on the changes that we introduce in the code.

**Comment by Luka-Loncar** [comment]
Reopened - lets do this from the beginning and create follow-ups @grantdfoster

**Comment by Luka-Loncar** [comment]
#246 is the follow up issue
