### ISSUE TITLE
Create Dune dashboard with Incentivized testnet winners

### ISSUE THREAD

**Issue by Luka-Loncar** [masa-finance/masa-bittensor#220]
From yesterday 29th August, we have sent out the message in Discord and via mail to our incentivized testnet miners to provide us with a .txt file which confirms the ownership of cold/hot/eth keys. This will run until 15th September, in order to give everyone chance to do this task. After that we will have correct list of the miners that should be rewarded, and from that list we should build Dune table with winners.

**Comment by teslashibe** [comment]
@hide-on-bush-x what is the status of this?
