### ISSUE TITLE
Miner subnet 42 registration resetting daily

### ISSUE THREAD

**Issue by omdano** [masa-finance/masa-bittensor#232]
**Masa-Bittensor version:**
0.7.0

**Environment, CPU architecture, OS, and Version:**
Linux third-one 6.8.0-41-generic #41-Ubuntu SMP PREEMPT_DYNAMIC Fri Aug  2 20:41:06 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux

**Describe the bug**
Same cold/hot wallet I run the miner with suddenly stops being registered one day into the mining. I regenerated the hot wallet using the mnemonic and its still de-registered. 

**To Reproduce**
Register hot wallet
Mine for ~24 hours

**Expected behavior**
Register hot wallet and it remains registered

**Comment by grantdfoster** [comment]
This is not a bug, this is how Bittensor is meant to function.  Each new registration has an immunity period of 17 hours, after which you are no longer "immune".  The worst performing miner gets booted when a new registration happens.
