### ISSUE TITLE
Spinning down the instances in GCP

### ISSUE THREAD

**Issue by Luka-Loncar** [masa-finance/masa-bittensor#235]
## Objective
Reduce our monthly Google Cloud Platform (GCP) bill by identifying and spinning down unnecessary instances and services.

## Timeline
Target completion date: Friday 13th September 2024.

## Steps
1. [ ] Document current GCP infrastructure
2. [ ] Review dependencies with services
3. [ ] Spin down infrastructure and shut off services
4. [ ] Confirm bill reduction

### Testnet Nodes

- [ ] New testnet - should be communicated with node operators to do the switch

## Infrastructure to be Spun Down
[To be filled out by John Durkin after internal review]

**Comment by 5u6r054** [comment]
Have removed 4 of 5 of the GCP bootnodes
Have removed 5 additional nodes that were not in use

There remain several instances that may be able to be removed, 
There remain a few databases that can probably be archived and turned off

**Comment by Luka-Loncar** [comment]
We have marked this issue as done, but I'm creating follow-up issue with other services and DBs and instances that could be shut down in next week. Cost of GCP can be reduced greatly in near feature. 
https://github.com/orgs/masa-finance/projects/7/views/1?pane=issue&itemId=80217603
