### ISSUE TITLE
Spike: How to best serve Validator API while considering security

### ISSUE THREAD

**Issue by Luka-Loncar** [masa-finance/masa-bittensor#243]
@teslashibe @5u6r054 to provide here some problem statement description

## Acceptance criteria

- [ ] Boolean API true/false - maybe false by default - first iteration 
- [ ] Second iteration is making the true state configurable

**Comment by hide-on-bush-x** [comment]
Follow up task: [#251](https://github.com/masa-finance/masa-bittensor/issues/251)
