### ISSUE TITLE
feat: autoupdate to latest code for miner and validator

### ISSUE THREAD

**Issue by teslashibe** [masa-finance/masa-bittensor#246]
This is for implementing: https://github.com/masa-finance/masa-bittensor/issues/208

## Acceptance criteria:

- [ ] Default is to "not update" automatically 
- [ ] A user can set a thread if code has updated when its running and can run when there is a diff
- [ ] New **_tagged_** release triggers the release

**Comment by Luka-Loncar** [comment]
Added to v1.0 as agreed
