### ISSUE TITLE
Create and run private validator for Masa so we can have better visibility

### ISSUE THREAD

**Issue by Luka-Loncar** [masa-finance/masa-bittensor#272]
I already set this up before in terraform:

https://github.com/masa-finance/masa-oracle-infra/tree/test/aws/opentensor

a set of terraform files and shell scripts that set up validators (on any env / network), miners, and subnet nodes (and several other infrastructure related components.

the nodes (including mainnet validator) are not currently running, and this ticket is really about updating the terraform and scripts due to many changes in bittensor since I first set it up, as well as security related updates

### Acceptance Criteria
- [x] Need to share hotkey with Brendan. 
- [x] Sync up the terraform for both testnet and mainnet, validators and miners they share dependencies. 
- [x] Need to register and run the validator once the delegation has been moved by Mog. 
- [ ] Figure out steps to stake and get up and running.

**Comment by grantdfoster** [comment]
note - need 1,000 staked TAO to test setting weights.  Anything above that is a nice to have

**Comment by Luka-Loncar** [comment]
Ok nice to know :)

**Comment by giovaroma** [comment]
Need to share with Mog hotkey to share with us we need @5u6r054 help. This is needed to get the validator up and running.

**Comment by 5u6r054** [comment]
shared a document with @teslashibe re: security considerations for the associated hot / cold keys and access to the machine, and the AWS account it is in.

**Comment by giovaroma** [comment]
Shared access to account and instance for secure access to validator. Need TAO to coldkey we register the validator. Once registered then Mog can delegate.

**Comment by giovaroma** [comment]
Stake delegated from TAO stats. Roll new code with 305 that is part of the release.
