### ISSUE TITLE
Update documentation after v1.0.2 release

### ISSUE THREAD

**Issue by Luka-Loncar** [masa-finance/masa-bittensor#275]
- We have agreed to call all miners - miners. We are just differentiating them on the product in which they are living:
- Protocol miner (instead of worker)
- Subnet miner - no change required here
- Sepolia ETH need to call faucet and stake should be more detailed
- we should have a link to some faucet - alchemy - https://www.alchemy.com/faucets/ethereum-sepolia
- explain that sepolia eth is needed for paying gas
- tell users that they need to pay gas for interacting with faucet and more eth to perform staking transaction
- warn users that tx fees are sometimes extremely high on sepolia 
- Warning not to use twitter accounts that you care about - since there is a risk of them being suspended (you can still scrape, but you can’t use it as normal person)
- Api enabled = true yes :slightly_smiling_face:
- That residental proxy thingy should be improved (explained better if its needed or not)
- Maybe we could clarify difference between cookie based and user/pass auth?
- This thing from Zac is maybe a nofix but check it pls - https://masafinance.slack.com/archives/C028C3D5FD3/p1729184663837619?thread_ts=1729178376.533099&cid=C028C3D5FD3
- New video - the old one is 0.8 version - but this is not a priority right now at all

**Comment by Luka-Loncar** [comment]
Also, here is a short loom video that is explaining what I found - not sure if this is intended or it should be fixed. WDYT @grantdfoster 

https://www.loom.com/share/5de9ed7b7bc04551b68fbd21fc993030

**Comment by giovaroma** [comment]
Almost complete
