### ISSUE TITLE
Failed to set weights: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

### ISSUE THREAD

**Issue by metabona** [masa-finance/masa-bittensor#279]
Failed to set weights: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all() - 

38|sn-42-vali-2  |   File "/root/masa-bittensor-92ltt/masa/utils/weights.py", line 209, in process_weights_for_netuid
38|sn-42-vali-2  |     logging.debug("non_zero_weights", *non_zero_weights)
38|sn-42-vali-2  |   File "/root/masa-bittensor-92ltt/bittensor/lib/python3.12/site-packages/bittensor/utils/btlogging/loggingmachine.py", line 437, in debug
38|sn-42-vali-2  |     self._logger.debug(msg, *args, **kwargs)
38|sn-42-vali-2  | Message: '0.37024685740470886 - non_zero_weights - 0.5668483972549438'
38|sn-42-vali-2  | Arguments: (np.float32(0.06290477),)

**Masa-Bittensor version:**
main: commit id: 23a811ad8ead66582fcc01c934eecb8a1d6ab30e

**Environment, CPU architecture, OS, and Version:**
ubuntu 22.04, python 12.3

**Describe the bug**
  Set weight error
input data debug:

uids: [0 1 2 3 4 5 6 7]
weights: [0.37024686 0.         0.         0.         0.         0.5668484 0.06290477 0.         ]

**To Reproduce**

**Expected behavior**
  I am running as a VALIDATOR in Local

**Logs**

38|sn-42-vali-2  |   File "/root/masa-bittensor-92ltt/masa/utils/weights.py", line 209, in process_weights_for_netuid
38|sn-42-vali-2  |     logging.debug("non_zero_weights", *non_zero_weights)
38|sn-42-vali-2  |   File "/root/masa-bittensor-92ltt/bittensor/lib/python3.12/site-packages/bittensor/utils/btlogging/loggingmachine.py", line 437, in debug
38|sn-42-vali-2  |     self._logger.debug(msg, *args, **kwargs)
38|sn-42-vali-2  | Message: '0.37024685740470886 - non_zero_weights - 0.5668483972549438'
38|sn-42-vali-2  | Arguments: (np.float32(0.06290477),)

**Additional context**

**Comment by metabona** [comment]
More log:


 ****** ^_^ ******* self.subtensor.set_weights |uids: [0 1 2 3 4 5 6 7] |weights: [0.36349228 0.         0.00941691 0.00941691 0.00941691 0.5087384
38|sn-42-v |  0.0995186  0.        ] |self.config.netuid: 2  |self.subtensor: subtensor(local, ws://127.0.0.1:9946) |self.metagraph: metagraph(netuid:2, n:8, block:114939, network:local) 
38|sn-42-v | 2024-10-16 06:45:11.214 |      DEBUG       | bittensor:loggingmachine.py:437 | quantile
38|sn-42-v | 2024-10-16 06:45:11.214 |      DEBUG       | bittensor:loggingmachine.py:437 | 1 - min_allowed_weights
38|sn-42-v | 2024-10-16 06:45:11.214 |      DEBUG       | bittensor:loggingmachine.py:437 | 1.0 - max_weight_limit
38|sn-42-v | 2024-10-16 06:45:11.216 |      DEBUG       | bittensor:loggingmachine.py:437 | 0.8333333333333334 - max_exclude
38|sn-42-v | 2024-10-16 06:45:11.216 |      DEBUG       | bittensor:loggingmachine.py:437 | exclude_quantile
38|sn-42-v | 2024-10-16 06:45:11.216 |      DEBUG       | bittensor:loggingmachine.py:437 | 0.009416909888386726 - lowest_quantile
38|sn-42-v | 2024-10-16 06:45:11.218 |      ERROR       | bittensor:loggingmachine.py:457 |  - Setting weights failed: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all() -

**Comment by grantdfoster** [comment]
appreciate the issue!  this has been solved in release 1.0.2.  It is a bug within the Bittensor library, in versions 8.1.0, 8.1.1, and 8.2.0.  We are submitting a PR to their repo today w/ the fix.
