### ISSUE TITLE
[ISSUE]: Validators to Index Scraped Tweets to API

### ISSUE THREAD

**Issue by grantdfoster** [masa-finance/masa-bittensor#305]
### Technical Description

- we need a central place to store mined tweets from the subnet
- validators locally index tweets currently, by query - we need to POST this to an API
- first pass at API is already built, needs to be tested

### Acceptance Criteria

- [x] Indexed tweets are available via an API
- [x] Validators automatically POST indexed tweets after scoring
- [x] Validators no longer store indexed tweets locally
- [ ] We will test on testnet.
- [ ] Weights update required and weeks notice starting today. Weights to be updated next week on Monday Dec the 9th. A new release required. The update is required.

### Implementation Details

- Send a POST request to the given API after a validator scores and indexes tweets
- Ensure the API has the ability to read / paginate tweets, by query

### Dependencies

- Masa protocol API

We are not removing the setting for the API end-point because the user can change it anyways.

**Comment by hide-on-bush-x** [comment]
Added exporting method to validator, its being called after processing tweets 
It sends:
```python
{
 "validator_metadata":  {
        "uid": number,
         "code_version": number,
         "last_healthcheck_block": number,
         "last_volume_block": number,
},
   "tweets": tweet[],
}
```
To the API Url defined in the config `--validator.export_url`

**Comment by hide-on-bush-x** [comment]
Removed cpu storage of tweets by query, but not sure if we should also remove the "tweets by uid" storage

What do you think @grantdfoster ?

**Comment by giovaroma** [comment]
@grantdfoster Indexed tweets are available via an API working on Go handed off to @teslashibe to help with some errors, other than that good to go on this acceptance criteria item.

**Comment by grantdfoster** [comment]
protocol API work is complete in https://github.com/masa-finance/masa-protocol-api/pull/11
will be testing integration with said API in this PR soon

**Comment by giovaroma** [comment]
Pointing validators to new API end-point.

**Comment by grantdfoster** [comment]
Both PRs are ready to go!  We just need to know the production URL to point the subnet to the right place.

https://github.com/masa-finance/masa-protocol-api/pull/11/files
https://github.com/masa-finance/masa-bittensor/pull/310

**Comment by giovaroma** [comment]
Weights update required and weeks notice starting today. Weights to be updated next week on Monday Dec the 9th. A new release required. The update is required.
