### ISSUE TITLE
Set Up API Documentation Hosting

### ISSUE THREAD

**Issue by Luka-Loncar** [masa-finance/masa-bittensor#35]
- Host the API documentation on platforms like SwaggerHub in GitHub Pages for accessibility.
- Push the documentation to a Category on Masa Developer docs using a GitHub Action
- Add a Domain for the EC2 instance where we have been running validator/miner/healthcheck
- Make sure the healthcheck API running on port 4000 has an SSL certificate ( requirement to be called from the vercel instance )

**Comment by grantdfoster** [comment]
Theoretically this ticket can be closed if we are able to access the `/docs` from the deployed validator.  @hide-on-bush-x is the validator still deployed at: `http://34.235.146.46:8000/docs`?  seems like it may have moved...

**Comment by hide-on-bush-x** [comment]
@grantdfoster Devnet lost state, I need to go through the whole process on that machine again

Will do it later today

**Comment by Luka-Loncar** [comment]
@hide-on-bush-x hey - how this went? Can we close the issue?

**Comment by hide-on-bush-x** [comment]
@Luka-Loncar Not yet, ill double check that the docs are accessible today

**Comment by mudler** [comment]
@5u6r054 can you help here maybe?

**Comment by hide-on-bush-x** [comment]
All clear now, validator is running on http://34.235.146.46:8000

To access docs everyone can go to http://34.235.146.46:8000/docs and it will be accessible, currently the validator is running on pm2

**Comment by mudler** [comment]
what is left here is to have a DNS for the swagger API's and link these to the masa developer docs for an example of the API endpoints.

**Comment by mudler** [comment]
There are still items left on this card to do

**Comment by Luka-Loncar** [comment]
We decided that this issue is not needed and therefore its closed.
