### ISSUE TITLE
SettingWeightsTooFast: Improve subtensor settings to have a better onboarding to the project

### ISSUE THREAD

**Issue by hide-on-bush-x** [masa-finance/masa-bittensor#38]
Currently it is required to wait a few hours to have everything working
I believe this can be improved from subtensor settings, its worthy to take a look

**Comment by mudler** [comment]
Blocked by #61

**Comment by grantdfoster** [comment]
This issue has been resolved by #96 - we are now able to change the `weights_rate_limit` to a lower value (`5`), thus allowing new users to set weights quicker when onboarding on devnet.  We discovered that validators do not get a `vpermit` until a `tempo` has passed, but that is outside of our control and is a guard we will experience on both `testnet` and `mainnet`.
