### ISSUE TITLE
Update documentation

### ISSUE THREAD

**Issue by juanmanso** [masa-finance/masa-bittensor#60]
## Description

Notion item:
- https://www.notion.so/masafinance/EPIC-Subnet-v0-0-2-alpha-fbc2d291be2b4e1fa46585eb014a3ef8?pvs=4#eb4f04c1ce94486598df45ab7523b201

## Acceptance Criteria
- Release Notes for v0.0.2-alpha contain the development on #58 and #59
- [If needed] Update internal docs with design decision made for either of those tasks
- [Nice to have] Tool to automatically generate Release notes based on PR titles and/or labels

**Comment by obasilakis** [comment]
Suggestion for handling releases. Let's use [python-semantic-release](https://python-semantic-release.readthedocs.io/en/latest/index.html). We would need to create a dev branch (or some other name) where we push our changes, and whenever we want to release, we push to main and the library takes care of updating the tag & release notes. Wyt @juanmanso @hide-on-bush-x @grantdfoster

**Comment by juanmanso** [comment]
As responded on Slack, i'd say you implement the workflow because at least we have something going until we say otherwise.

My 2 cents here is to consider something as straight forward as [Release Drafter GH Action](https://github.com/release-drafter/release-drafter) but don't know the assessment you made for semantic release and if it's better or not.

Also don't understand if the `python-semantic-release` is a per PR thing or per commit 🤔. I'd stick to PR-based changelog/changesets but I think that is worth discussing with the team as a whole

**Comment by juanmanso** [comment]
Closing this ticket since main acceptance criteria was met on #80 and discussion remains on NTH items.

- Closed by #80 
- Continued on #83
