### ISSUE TITLE
spike: Research Bittensor Hyperparameters

### ISSUE THREAD

**Issue by Luka-Loncar** [masa-finance/masa-bittensor#61]
## Problem: 

We do not understand which hyperparameters need setting for a subnet in order to go to production in July

## Objective:

Investigate and understand the purpose, usage, and impact of all of Bittensor hyperparameters

Bittensor documentation: https://docs.bittensor.com/subnets/subnet-hyperparameters

## Acceptance Criteria:

- [ ] Research is conducted for each of the specified hyperparameters.
- [ ] Findings are documented, including the purpose, usage, and impact of each hyperparameter.
- [ ] Recommendations for optimal settings are provided based on the research.
- [ ] A summary of the findings is compiled, discussing potential trade-offs and considerations.
- [ ] Create EPIC and tickets for setting hyperparameters 
   - [ ] Devnet
   - [ ] Testnet
   - [ ]  Main

This SPIKE ticket will help gain a deeper understanding of these crucial Bittensor hyperparameters, enabling informed decisions when configuring and optimizing the Bittensor subnet.

**Comment by H34D** [comment]
> ## Summary
> Adjusting these hyperparameters involves balancing performance, security, and fairness. Higher `min_allowed_weights` and `max_weight_limit` promote balanced validator activity, while `immunity_period` and `activity_cutoff` ensure stability and active participation. Optimal settings vary by subnet needs, and careful monitoring post-adjustment is crucial for maintaining desired network dynamics.

i am assuming they must be set by the subnet owner account / role. right?

**Comment by mudler** [comment]
seconding @H34D thoughts - few Q pops up in my head here:

- where are we going to set those hyperparameters to take effect?
- the user must be aware of these settings? shall we expose it to the user and be documented?

**Comment by hide-on-bush-x** [comment]
@H34D Yes, this settings are set by the owner if the subnet
@mudler we should start setting this params in one of our devnet subnets as a first experiment
This hyperparameters can be seen by the user using the CLI

something like 
```bash
btcli subnet hyperparameters --netuid 1 --subtensor.chain_endpoint  ws://54.205.45.3:9945
```

```bash
   Subnet Hyperparameters - NETUID: 1 - unknown
 HYPERPARAMETER              VALUE
   rho                       10
   kappa                     32767
   immunity_period           5000
   min_allowed_weights       1
   max_weight_limit          65535
   tempo                     360
   min_difficulty            18446744073709551615
   max_difficulty            18446744073709551615
   weights_version           0
   weights_rate_limit        100
   adjustment_interval       360
   activity_cutoff           5000
   registration_allowed      True
   target_regs_per_interval  1
   min_burn                  1
   max_burn                  100000000000
   bonds_moving_avg          900000
   max_regs_per_block        1
   serving_rate_limit        50
   max_validators            64
   adjustment_alpha          17893341751498265066
   difficulty                18446744073709551615
```


I will test `weights_rate_limit` by setting weights for a set of miners and then removing the rate limit after I get the error about "setting weights too fast" ( Will post my findings here )
