### ISSUE TITLE
Weights Setting & Weight Logic

### ISSUE THREAD

**Issue by Luka-Loncar** [masa-finance/masa-bittensor#62]
This builds on @Hide on bush ‘s SPIKE for weights here: 

https://github.com/masa-finance/bittensor-1/issues/49

### Objective:

The problem is we don't understand what impact setting weights has and we don't understand how to do it where it works and if it's working in the current feature branch. This spike is not about getting weights, setting a weight logic working right now. It's about understanding the impact of it, understanding how we set it, and what it means on DevNet, what it means on TestNet, what it means on MainNet

### Tasks:

- [ ]  **Investigate Current Issues**
    - Identify the root cause of the malfunctioning weights setting.
- [ ]  **Propose a Solution**
    - Create a plan to resolve the issue and ensure fair and efficient network operation.
- [ ]  **Update Documentation**
    - Document the changes made and update the relevant sections of the project documentation.

### Acceptance Criteria:

- Weights setting mechanism functions as expected, ensuring fair and efficient network operation.
- The solution is thoroughly accepted and documented.

**Comment by Luka-Loncar** [comment]
@hide-on-bush-x please leave your comments here.

**Comment by mudler** [comment]
The PR looks good here, however missing a status update from @hide-on-bush-x - reopening
