### ISSUE TITLE
Simulation in Notebook

### ISSUE THREAD

**Issue by Luka-Loncar** [masa-finance/masa-bittensor#65]
After we have completed our spike in https://github.com/masa-finance/masa-bittensor/issues/11, we want to have a simulation of the rewards in a notebook so we can visualize the results and sharing those around (with the community, and other stakeholders).

## Action Items

- [x] We have a notebook that can be used in Deepnote
- [ ] The notebook source code is added to a simulation specific repo.

**Comment by mudler** [comment]
Blocked by https://github.com/masa-finance/masa-bittensor/issues/65

**Comment by theMultitude** [comment]
@Luka-Loncar I suspect I'll own this unless @teslashibe says otherwise.  Also, I changed the ticket this morning reflect we'll try and keep experimentation notebooks in [Deepnote](https://deepnote.com/workspace/masa-analytics-d68a9273-a2c8-45ce-9e9d-355017b5d9ef/getting-started)

**Comment by Luka-Loncar** [comment]
Great to hear! If you want to pick it up that is more than welcome.

**Comment by theMultitude** [comment]
> Blocked by https://github.com/masa-finance/masa-bittensor/issues/65

To clarify, this ticket is issue 65, yeah? Can you point me to the blocker or is it resolved?

**Comment by theMultitude** [comment]
@Luka-Loncar The project has been created [here](https://deepnote.com/workspace/masa-analytics-d68a9273-a2c8-45ce-9e9d-355017b5d9ef/project/Bittensor-Rewards-Simulation-f017507a-86ad-40cb-8efa-5587c78ee158/notebook/Rewards%20Simulation-050b095454c747ab985ac57fdd5675ed?secondary-sidebar=versions).  I just want to confirm the repo we want it to be associated with before finalizing the link.

**Comment by Luka-Loncar** [comment]
Good question, I would ask @mudler to provide suggestions on this. We are usually using private repos if we don't want something to be visible.

**Comment by Luka-Loncar** [comment]
Ok, lets do it like that.

@theMultitude is there any triage or any other info that you require from product in order to tackle this one?

**Comment by theMultitude** [comment]
@mudler in my mind this information isn't necessary as part of this public repo and would sit more neatly in a data science/experimentation repo that won't need to be surfaced in the same way.  It also helps me to orchestrate and support experimentation in a more centralized way if we have a dedicated repo for it. Experiments and methodology can be surfaced through publications once a bit more polished.

**Comment by mudler** [comment]
> @mudler in my mind this information isn't necessary as part of this public repo and would sit more neatly in a data science/experimentation repo that won't need to be surfaced in the same way. It also helps me to orchestrate and support experimentation in a more centralized way if we have a dedicated repo for it. Experiments and methodology can be surfaced through publications once a bit more polished.

makes sense here :+1:

**Comment by theMultitude** [comment]
@Luka-Loncar a pull request to add the notebook. https://github.com/masa-finance/masa-bittensor/pull/114

I think we may want to centralize this type of work sooner rather than later as mentioned [above](https://github.com/masa-finance/masa-bittensor/issues/65#issuecomment-2181048467) but I didn't want to block y'all from getting started.

**Comment by Luka-Loncar** [comment]
Thanks! 

What would that centralization look like? Can you please explain it in a bit more detail?

**Comment by theMultitude** [comment]
@Luka-Loncar As mentioned [here](https://github.com/masa-finance/masa-bittensor/issues/65#issuecomment-2181048467) I'd like to have a repo dedicated to data science work at Masa.  It would make it easier for me to consult and contribute to related types of work.

**Comment by Luka-Loncar** [comment]
I don't think that it would be any kind of issue that you have your own repo. 

@mudler do you have anything against that maybe?

@theMultitude can we close this ticket now?

**Comment by mudler** [comment]
@theMultitude sounds good here - can you create the repo? or shall I?

**Comment by theMultitude** [comment]
@mudler I can tomorrow morning. @Luka-Loncar I'll close it when I finish.

**Comment by mudler** [comment]
I see also https://github.com/masa-finance/masa-bittensor/pull/114 still open tied to this

**Comment by juanmanso** [comment]
I think since the #114 PR is merged, we can close this
