### ISSUE TITLE
Remove annoying type warnings

### ISSUE THREAD

**Issue by obasilakis** [masa-finance/masa-bittensor#76]
![Image](https://github.com/masa-finance/masa-bittensor/assets/33531476/9a5d3314-ecdb-4f65-99b1-ac94059ccbf9)

Get rid of these warnings

**Comment by obasilakis** [comment]
Warnings come from within bittensor lib. After some effort we decided to backlog it for now.

**Comment by juanmanso** [comment]
> Warnings come from within bittensor lib. After some effort we decided to backlog it for now.

Need to test with newest version `7.2.0` to determine if its fixed or not. From what I recall it doesn't fix it so this should be looked at on every new release of Bittensor (or monitor their discord)

**Comment by juanmanso** [comment]
As shown below, for my current setup using `7.2.0` the warnings are no longer shown.

| _Test on miner with btcli `7.2.0`_ |
| :--: |
| ![Image](https://github.com/masa-finance/masa-bittensor/assets/21087992/eb3cb9f8-28c1-4bd8-ae00-2b30e9fb0308) |


I'd ask for someone on the @masa-finance/subnet team to test themselves just to be sure it's not a local fix. Moving it to `In Review`

**Comment by Luka-Loncar** [comment]
We are leaving it here until someone gets available to review.

**Comment by Luka-Loncar** [comment]
Wontfix - agrred on planning
