### ISSUE TITLE
Hyperparameters Testing Subnet 

### ISSUE THREAD

**Issue by hide-on-bush-x** [masa-finance/masa-bittensor#77]
# This is a follow up task from #61 

Since the hyperparameters research spike came from some difficulties at the time of setting weights:
- It is required to create a subnet where hyperparameters settings allow us to set weights from the subnet validator
- This may require updating code in order to avoid errors and do the weight setting as simple as possible

Where to watch:
- #61 For needed hyperparameters information
- #49 For the problems we found on setting weights
- `masa/base/validator.py/BaseValidatorNeuron#set_weights`

Acceptance criteria:
- [ ] A new subnet where setting weights works
- [ ] Instructions about how setting weights work on that subnet
- [ ] A validator can set weights every after 5 blocks
- [ ] Validators and Miners get incentives 
- [ ] Validators can set weights after calculating rewards in the current flow
- [ ] Weights set are visible through the metagraph

## How to validate/test that weights are being stored:
You should be able to see your weighs in your corresponding row of the matrix
```python
import bittensor as bt
wallet = bt.wallet(<WALLET_NAME>)
subnet = bt.metagraph(<NETUID>, 'ws://54.205.45.3:9945', lite=False)
subtensor = bt.subtensor('ws://54.205.45.3:9945')

### To set weights
subtensor.set_weights(wallet=wallet, netuid=<NETUID>, uids=[1], weights=[0.1])

### To read the matrix of weights
subnet.sync()
print(subnet.W)
```

**Comment by mudler** [comment]
>  A validator can set weights every after 5 blocks

This is not completely clear to me (why? is this a limitation?)

> @mudler any insights here?

Ticket looks good here :+1:

**Comment by hide-on-bush-x** [comment]
It would be awesome if some of us could open ports and test this with at least a few validators and miners on testnet

**Comment by juanmanso** [comment]
> It would be awesome if some of us could open ports and test this with at least a few validators and miners on testnet

Sure, I'll help out running a miner. Need to setup the port opening but that should be simple enough 😅

**Comment by Luka-Loncar** [comment]
@teslashibe can you help with testing here? @5u6r054 same question for you?

**Comment by Luka-Loncar** [comment]
Closing this task since we don't care about scalability in v0.5. 

I'm creating follow up task to test scalability later:
