### ISSUE TITLE
Add new set of Discord endpoints from latest protocol version

### ISSUE THREAD

**Issue by Luka-Loncar** [masa-finance/masa-bittensor#81]
Slack thread for reference: https://masafinance.slack.com/archives/C05P6TREBTJ/p1718185055360969

We haven't implemented the latest endpoints that were added to the new Masa Protocol release. The agreement was to go with what we have, and then add missing endpoints in the next iteration.

**Comment by teslashibe** [comment]
This ticket is blocked by the implementation of this spike https://github.com/masa-finance/masa-bittensor/issues/71

**Comment by mudler** [comment]
@obasilakis what's the status here?

**Comment by Luka-Loncar** [comment]
This is done, but I would like that we have some comment from @obasilakis when he is back.
