### ISSUE TITLE
spike: research how vtrust and vpermit works

### ISSUE THREAD

**Issue by teslashibe** [masa-finance/masa-bittensor#88]
We currently see that miners on our network get vtrust which implicitly makes them validators.

Research how vtrust gets set for both a validator and miner, an miner should not get vtrust otherwise it is a validator or miner/validator

**Comment by teslashibe** [comment]
Ask in Discord

**Comment by grantdfoster** [comment]
Tracking conversation [here](https://discord.com/channels/1120750674595024897/1242998080501186620/1250576710039244851)

**Comment by grantdfoster** [comment]
Based on the conversation in Discord, the Testnet may be configured in such a way that there is no minimum TAO required to acquire a vpermit.  Attempted to compare hyperparameters between devnet and testnet, but the call:

`btcli subnets hyperparameters --subtensor.$(SUBTENSOR_ENVIRONMENT) --netuid $(NETUID)`

is failing on devnet.  creating a fresh miner now on devent to see the `vpermit` behavior

**Comment by grantdfoster** [comment]
After doing some work with miner-2, we see that it now has a `vpermit`!  Interesting because no staked TAO appears on miner-2, but perhaps it's a super small amount.  Will pivot into more research

![Screenshot 2024-06-13 at 11 02 36 AM](https://github.com/masa-finance/masa-bittensor/assets/18288572/eeb90acb-bcca-4896-8ed2-f1621f89c8a3)

**Comment by grantdfoster** [comment]
## Research

### VPermit
- **Dynamic Competition**: The minimum stake required to obtain a VPermit is dynamically determined based on the stakes of the top "x" validators in a given subnet. This means that the minimum stake is the stake of the "x"th highest staked neuron within that subnet.  This is why once a miner does work and has staked TAO as a result, they are marked w/ a vpermit.
- **Observation**: We can set a minimum amount of staked TAO required to be considered a validator by a miner to ensure that initial miners aren't considered validators.

### VTrust
- **Description** measure of a neuron's reputation within the network. It is calculated based on various factors including the neuron's historical activity, the accuracy of its validations, and its overall contribution to the network's health.

### Validator / Miner Identification
- **VPermit Status**: If a neuron has a VPermit, it is authorized to act as a validator.
- **Stake Amount**: Generally, validators have higher stakes compared to miners, reflecting their greater responsibilities and the trust placed in them by the network.
- **Activity Logs**: By examining the types of tasks a neuron performs (validating transactions vs. performing computational tasks for the network), you can distinguish between validators and miners.

**Comment by grantdfoster** [comment]
Adding a stake check on the `synapse` can look like the following in miner/forward.py:

```python
# Get the current stakes from the metagraph
        current_stakes = self.metagraph.S

        # Define the minimum stake required
        min_stake = 1000  # Adjust this value as needed

        # Check if the calling neuron meets the minimum stake requirement
        caller_uid = self.metagraph.hotkeys.index(synapse.dendrite.hotkey)
        if current_stakes[caller_uid] < min_stake:
            bt.logging.warning(f"Rejecting synapse from neuron with insufficient stake: {current_stakes[caller_uid]}")
            return synapse  # You might want to modify the response to indicate rejection
```

**Comment by hide-on-bush-x** [comment]
It looks like applying that min_stake may be the way to go, have you done any research about what kind of minimums are other subnets using? 

Based on that we should be able to create a task for implementation

**Comment by teslashibe** [comment]
Really great work here @grantdfoster - lets do an implementation ticket and move this forward. 

I am adding `min_stake` checks to our production release checklist here: https://github.com/orgs/masa-finance/projects/12/views/1?pane=issue&itemId=66418693

cc @Luka-Loncar
