### ISSUE TITLE
V2 - Implement Request Sending Mechanism in forward.py

### ISSUE THREAD

**Issue by Luka-Loncar** [masa-finance/masa-bittensor#9]
- **V2 Performance-Based**: Choose miners based on their historical performance metrics such as response accuracy, response time, and reliability. This can incentivize miners to maintain high performance.
- Construct the query using the class from `protocol.py`, ensuring the request adheres to the subnet's protocol.

**Comment by mudler** [comment]
Closing as not relevant anymore
