### ISSUE TITLE
Community competition to be the largest staked validator on Devnet

### ISSUE THREAD

**Issue by teslashibe** [masa-finance/masa-bittensor#91]
We want to simulate validator behavior on Devnet

**Comment by mudler** [comment]
moving back to backlog until this card is groomed out

**Comment by juanmanso** [comment]
Not enough info to be groomed/assessed. Would suggest to leave it on `No Status` until Stakeholders/Roadmap Owners provide more info

**Comment by juanmanso** [comment]
> Not enough info to be groomed/assessed. Would suggest to leave it on `No Status` until Stakeholders/Roadmap Owners provide more info

+1

**Comment by juanmanso** [comment]
> > Not enough info to be groomed/assessed. Would suggest to leave it on `No Status` until Stakeholders/Roadmap Owners provide more info
> 
> +1

+1

Knowing that there is currently a competition on `miner` behavior, this might be relevant. Thus, I'm not moving it to review since we might still need more info here.

**Comment by juanmanso** [comment]
> > > Not enough info to be groomed/assessed. Would suggest to leave it on `No Status` until Stakeholders/Roadmap Owners provide more info
> > 
> > 
> > +1
> 
> +1
> 
> Knowing that there is currently a competition on `miner` behavior, this might be relevant. Thus, I'm not moving it to review since we might still need more info here.

This might be ready to be closed since the competition is already bringing data on how the validator/miner relationship is going, what does the team think?

**Comment by Luka-Loncar** [comment]
This is obsolete now.
