### ISSUE TITLE
Define Hyperparameters for dev environment

### ISSUE THREAD

**Issue by Luka-Loncar** [masa-finance/masa-bittensor#95]
Spike ticket: https://github.com/orgs/masa-finance/projects/7/views/1?pane=issue&itemId=66775203

**Comment by mudler** [comment]
From planning session: 

This tickets is only missing documentation updates at this point - moving to in Progress as @grantdfoster is going to work on it

**Comment by grantdfoster** [comment]
- initial documentation added for hyperparameter setup, #110

**Comment by grantdfoster** [comment]
edits to this ticket have been ported / captured in https://github.com/masa-finance/masa-bittensor-tools/pull/12.  once reviewed and merged we are free to close this.

**Comment by grantdfoster** [comment]
PR merged and closed
