### ISSUE TITLE
bug: Devnet Hyperparameters

### ISSUE THREAD

**Issue by grantdfoster** [masa-finance/masa-bittensor#96]
cc: @Luka-Loncar @5u6r054 
## Description

- unable to set `weights_rate_limit` on `devnet`
- we _are_ able to set `weights_rate_limit` on `testnet`, suspecting we need to upgrade `devnet` to latest

## Solution
- upgrade `devnet` to the [latest release](https://github.com/opentensor/subtensor)
- @grantdfoster to re-attempt setting new rate limit via:
```bash
btcli sudo set --param weights_rate_limit --value 5 --netuid 1 --subtensor.chain_endpoint ws://54.205.45.3:9945
```
- this should also solve the issue of not being able call `btcli subnets hyperparameters` on `devnet`

**Comment by grantdfoster** [comment]
Still seeing the same issues after the upgrade to `main`, will find out the build that `testnet` currently uses so we can replicate

**Comment by 5u6r054** [comment]
Found out testnet is running v1.1.0. Tested running devnet on this version, which is older, and we got invalid block errors. 

Learned that current main version of subnet works well, but only if we start our data over again with a fresh empty chain.

We decided to move forward with clean chain.

**Comment by grantdfoster** [comment]
Update, per this thread, we are now running subtensor v1.1.2 (latest main) and the latest btcli 7.2.0.  I'm setting up the subnet 1 now and attempting to adjust rate limiting

**Comment by grantdfoster** [comment]
- after the upgrade, we confirmed that hyperparams correctly are set and working
- set our `weights_rate_limit` to `5`
- verified that it takes 1 tempo for staked validators to get their permit... nothing we can do as a tempo duration is not editable
